# Update tool version

# Suppose, that script is here -> /root/Scripts/script.sh
# $0 -> Script path. (./script.sh ) # relative path to a directory from where you call it.
# realpath $0 -> Absolute path to script ( from root ), /root/Scripts/script.sh
# dirname $(realpath $0) - Absolute path to Script folder. ( /root/Scripts )
# dirname $(dirname $(realpath $0)) - Absolute path to Script parent folder. ( /root/ )
cd $(dirname $(dirname $(realpath $0)))

echo "Traveling to directory $(pwd)"

TOOL_VERSION_FILE_NAME='Version.swift'

echo "Searching for a tool version file."
TOOL_VERSION_FILE=$(find ./ -name ${TOOL_VERSION_FILE_NAME})
echo "I've found a tool version file. ${TOOL_VERSION_FILE}"

echo "Lookup into a git for a valid tag"
LAST_VERSION_TAG=$(git describe --always --tags --dirty)
echo "I have last version tag. ${LAST_VERSION_TAG}"

echo "Pouring version into version file"
FORMATTED_VERSION=$"// Do not delete this code. Autogenerated by script.
// Run \`sh ./Scripts/update_version.sh\` instead.
public let ToolVersion = \"${LAST_VERSION_TAG}\""

echo "Output will be ${FORMATTED_VERSION}"
echo "${FORMATTED_VERSION}" > ${TOOL_VERSION_FILE}